name: '🚛 deploy'
description: '내가 지정한 호스트의 프로젝트 폴더 git pull origin develop! & Release deploy-src.tar 폴더 압축 해제 덮어쓰기'

inputs:
  # https://github.com/dsaltares/fetch-gh-release-asset/blob/master/action.yaml
  # 해당 액션 참고 
  repo:
    description: 'The `org/repo` containing the release.'
    required: false
    default: ''
  version:
    description: 'The release version to fetch from in the form `tags/<tag_name>` or `<release_id>`.'
    required: false
    default: 'latest'
  file:
    description: 'The name of the file to be downloaded.'
    required: true
  target:
    description: 'Target file path.'
    required: false
  token:
    description: 'The GitHub token. Typically this will be secrets.GITHUB_TOKEN'
    required: true

runs:
  using: "composite"
  steps:
    - run: echo Hello World.
      shell: bash
