#!/bin/bash


DEPLOY_KEY=$INPUT_DEPLOY_KEY
if ! [[ -z ${INPUT_DEPLOY_KEY} ]]; then
  DEPLOY_KEY=$DEPLOY_KEY
fi

USERNAME=$INPUT_USERNAME
if ! [[ -z ${INPUT_USERNAME} ]]; then
  USERNAME=$INPUT_USERNAME
fi

SERVER_IP=$INPUT_SERVER_IP
if ! [[ -z ${INPUT_SERVER_IP} ]]; then
  SERVER_IP=$INPUT_SERVER_IP
fi

SERVER_DESTINATION=$INPUT_SERVER_DESTINATION
if ! [[ -z ${INPUT_SERVER_DESTINATION} ]]; then
  SERVER_DESTINATION=$INPUT_SERVER_DESTINATION
fi

ARGS=$INPUT_ARGS
if ! [[ -z ${INPUT_ARGS} ]]; then
  ARGS=$INPUT_ARGS
fi

SERVER_PORT=$INPUT_SERVER_PORT
if ! [[ -z ${INPUT_SERVER_PORT} ]]; then
  SERVER_PORT=$INPUT_SERVER_PORT
fi

FOLDER=$INPUT_FOLDER
if ! [[ -z ${INPUT_FOLDER} ]]; then
  FOLDER=$INPUT_FOLDER
fi

set -eu

SSHPATH="$HOME/.ssh"
mkdir -p "$SSHPATH"
echo "$DEPLOY_KEY" > "$SSHPATH/key"
chmod 600 "$SSHPATH/key"
SERVER_DEPLOY_STRING="$USERNAME@$SERVER_IP:$SERVER_DESTINATION"
# sync it up"
sh -c "rsync $ARGS -e 'ssh -i $SSHPATH/key -o StrictHostKeyChecking=no -p $SERVER_PORT' $GITHUB_WORKSPACE/@sync/$FOLDER $SERVER_DEPLOY_STRING"
